# 配置应用名称
spring:
  application:
    name: gateway-zuul
server:
  port: ${port}
# Eureka注册中心配置
eureka:
  client:
    service-url:
      defaultZone: ${eureka.server}
  instance:
    hostname: localhost
    prefer-ip-address: true
    # 自定义Eureka名称
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#zuul:
  #组织敏感请求头传递到下游微服务中
  #sensitive-headers: 
management: 
  security: 
    enabled: false
#Hystrix超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#Zuul使用ribbon作为负载均衡，配置ribbon超时时间
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000