spring:
  application:
    name: consumer-movie-ribbon-custom-by-properties
server:
  port: ${port}
eureka:
  client:
    service-url:
      defaultZone: ${eureka.server}
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#服务的ServiceID.ribbon为前缀 设置负载策略
spring-cloud-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule